name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ main ]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      # Checkout code step
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Docker step
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
  
      # Log in to GitHub Container Registry using the provided credentials
      - name: Login to GitHub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      # Generate Docker image metadata, including tags and labels
      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ secrets.USERNAME }}/horizon_ui/horizon-ui
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value={{sha}},enable=${{ github.ref_type != 'tag' }}
      
      # Build and push the Docker image to the registry
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./prod.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}